#cpdr_plots_fxns.R

# This file contains functions for obtaining epidemiological measures from California's Parkinsons Disease Registry
# Input files: CPDR_acs_county_2017.rda (census data)
# Output files: plots for county ranking of Prevalence Rates

# Update priorities: Race Ethnicity demographic updates, date formatting updates, AddressCountyNme -> Cities -> census_tract data
#                    Facilities Reports, Timeliness, Time projection, 
# unique records, total records sent, unique facilities


countyRank_plot <- function(tmp_df, plot_title, myMeasure){ #the shape_df file generated by the cpdr_measures_fxn that creates the prevalence table
  if(myMeasure == "prev_rt"){
    p <- ggplot(tmp_df@data, aes(x = reorder(NAME, prevalence_rt), y = prevalence_rt)) + 
    geom_bar(stat = "identity", fill = "#59BEE3") +
    coord_flip() +
    labs (title = plot_title
          , x = "County"
          , y = "Prevalence Rate") +
    scale_fill_gradientn(colours=rev(brewer.pal(5, "RdYlBu"))) + 
    theme(plot.title = element_text(hjust = 0.5)
          , axis.text.x = element_text(angle = 45, hjust = 1)
          , panel.background = element_blank()) 
    p <- p + geom_hline(yintercept = (sum(tmp_df@data$Freq, na.rm=TRUE)*100000)/sum(tmp_df@data$estimate, na.rm = TRUE)) +
    scale_y_continuous(breaks = as.numeric(sort(c(seq(0
                                                      , max(tmp_df@data$prevalence_rt, na.rm = TRUE)
                                                      , by = 200)
                                                  , sprintf("%.0f", (sum(tmp_df@data$Freq, na.rm=TRUE)*100000)/sum(tmp_df@data$estimate, na.rm = TRUE))
                                                  )
                                                )
                                           )
                       ) +
    geom_text(aes(y = (sum(tmp_df@data$Freq, na.rm=TRUE)*100000)/sum(tmp_df@data$estimate, na.rm = TRUE)
                  , x = 6
                  , label = "California Estimate")
               , angle = 270
               , vjust = -1.2
    )} else {if(myMeasure == "case_cnt"){
      p <- ggplot(tmp_df@data, aes(x = reorder(NAME, Freq), y = Freq)) + 
        geom_bar(stat = "identity", fill = "#59BEE3") +
        coord_flip() +
        labs (title = plot_title
              , x = "County"
              , y = "Reported Cases") +
        scale_fill_gradientn(colours=rev(brewer.pal(5, "RdYlBu"))) + 
        theme(plot.title = element_text(hjust = 0.5)
              , axis.text.x = element_text(angle = 45, hjust = 1)
              , panel.background = element_blank()) 
      p <- p + geom_hline(yintercept = mean(tmp_df@data$Freq, na.rm = TRUE)) +
        scale_y_continuous(breaks = as.numeric(sort(c(seq(0
                                                          , max(tmp_df@data$Freq, na.rm = TRUE)
                                                          , by = 500)
                                                      , sprintf("%.0f", (mean(tmp_df@data$Freq, na.rm = TRUE)))
                                                      )
                                                    )
                                               )
                           )
    }}
  return(p)
}

# countyFreq_plot <- function(tmp_df, plot_title){
#   p <- ggplot(tmp_df@data, aes(x=reorder(NAME, prvlnc_), y = Freq, fill = prvlnc_)) +
#     geom_bar(stat = "identity")+
#     coord_flip() +
#     labs (title = plot_title
#           , x = "County"
#           , y = "Count") +
#     scale_fill_gradientn(colours=rev(brewer.pal(3, "RdYlBu")))
#   return(p)
# }

#Need to revise and edit plot for facility reports

# facilityTime_plot <- function (tmp_df, facility_list, demo_param, plot_title){ #cpdr_index based dataframe
#   # tmp_df <- filter(cpdr_index, ReportingFacilityName %in% facility_list) #Criteria for selecting only cases from the facility
#   # tmp_df <- tmp_df[tmp_df$DateLoaded >= cpdr_index$DateOfDiagnosis] #Criteria for removing cases that happened in the future (unlikely), need to report cases that qualitatively did not have correct cases for diagnosis
#   # #sum of cases with: (NA for Date of Diagnosis) + (cases with Date of Diagnosis > DateLoaded) + (cases with DOB as Date of Diagnosis) + (cases after July 2018 deadline) & no intercepts...
#   # # dx_errors <-
#   # difftime(cpdr_index[which(cpdr_index$DateLoaded >= cpdr_index$DateOfDiagnosis),])
# 
#   p <- ggplot(aes(tmp_df), color = demo_param) +
#     geom_histogram(fill = "#59BEE3" #some parameter here
#                   , alpha = 0.5) + #to be input for change later
#     geom_vline(aes(xintercept = mean())
#               , color = "blue"
#               , linetype = "dashed"
#               , size = 1) +
#     theme(panel.background = element_blank()) +
#     labs(title = plot_title
#          , x = "Count"
#          , y = "Time to Reporting")
# 
#   return(p)
# }

# 
# p <- ggplot(shape_df@data, aes(x=reorder(NAME, prevalence_rt), y = prevalence_rt, fill = Freq)) +
#   geom_bar(stat = "identity")+
#   coord_flip() +
#   labs (title = "County Rank"
#         , x = "County"
#         , y = "Prevalence Rate") +
#   scale_fill_gradientn(colours=rev(brewer.pal(3, "RdYlBu")))
# p

# writePlot <- function(plot_fxn= NULL, file_path = file.path(getwd())){
#   
# }



#####Plots for County Reports #####

#Rates by Sex & Age groups in California/County per 100,000



